version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "trigger-build-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sy59q7ox8l9"
s3_prefix = "trigger-build-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
