AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  triggerbuild

  Sample SAM Template for triggerbuild
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TriggerBuildFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: trigger-build/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        TriggerBuildSchdule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Name: trigger-build-schedule
            Description: Amplify on demand build schedule
            Enabled: True

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TriggerBuildFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TriggerBuildFunction.Arn
  TriggerBuildFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TriggerBuildFunctionRole.Arn
